### ISSUE TITLE
[Not An Issue] TF2Maps thread

### ISSUE THREAD

**Issue by 404UserNotFound** [crashfort/HammerPatch#1]
Hey there! Didn't see any thread on TF2Maps for this, shortly after I discovered the Facepunch thread for this program this morning, so I went ahead and made one that links to the Facepunch thread:

https://tf2maps.net/threads/hammerpatch-no-more-precision-loss-for-brush-vertices.32826/

I couldn't find you on Steam and I'm kinda permabanned from Facepunch (because of old stuff I'm not proud of), and I also couldn't find you on TF2Maps either so I figured I'd pop a quick thread up to spread the word about this patch.

Feel free to trash this issue or what-have-you when you've read it. Side question, am I correct in my assumptions that you used the old Source Engine 2007 leak for this? ( https://tf2maps.net/posts/417189/ ). I haven't used this patch yet but I can't wait to try it out :D

**Comment by crashfort** [comment]
Thank you for sharing it! I didn't post it on other forums as it can be seen rude to register just to post your own application.

And no, you are not entirely right about that. This is reverse engineered with the latest Hammer available with only references from the leak. Nothing is recompiled.

**Comment by 404UserNotFound** [comment]
Ah, neat! Well this is wonderful, it's now my go-to for mapping :D

**Comment by 404UserNotFound** [comment]
Had a friend on Reddit make some threads in various subs;

- [/r/Steam](https://www.reddit.com/r/Steam/comments/6fq5rk/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/SourceEngine](https://www.reddit.com/r/SourceEngine/comments/6frfy7/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/Hammer](https://www.reddit.com/r/hammer/comments/6frdya/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/TF2](https://www.reddit.com/r/tf2/comments/6fq33y/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/CounterStrike](https://www.reddit.com/r/counterstrike/comments/6fq999/cssgo_attn_mappers_hammerpatch_a_new_custom/?ref=share&ref_source=link)
- [/r/GlobalOffensive](https://www.reddit.com/r/GlobalOffensive/comments/6frhi4/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/CSMapMakers](https://www.reddit.com/r/csmapmakers/comments/6fqht6/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/HalfLife](https://www.reddit.com/r/HalfLife/comments/6ftod2/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=link)
- [/r/L4D2](https://www.reddit.com/r/l4d2/comments/6ftj2o/attn_mappers_hammerpatch_a_new_custom_version_of/?ref=share&ref_source=lin) (Stickied)
