### ISSUE TITLE
Decompiled maps made in Hammer break when loaded into HammerPatch

### ISSUE THREAD

**Issue by 404UserNotFound** [crashfort/HammerPatch#2]
This was posted in the TF2Maps thread: https://tf2maps.net/posts/417661/

"This breaks decompiled maps, most of the stuff turns into invalid solids"

I don't have any other info on the issue.

**Comment by crashfort** [comment]
Is this really an issue? Decompiled maps are not something you actually work with, other than possibly viewing so it's out of the purpose for this program.

**Comment by 404UserNotFound** [comment]
I actually work with decompiled maps the odd time. For example, pulling a setup of a fully mapped minigame from a trade map to turn it into a prefab for use in other maps. Heck, some people even decompile Valve maps for purposes. I once decompiled 2Fort to try to turn it into "achievement_idle_2fort" by modifying different areas of the map.

To each his own, I guess?

**Comment by SharpOB** [comment]
I've not encountered any issues working with a decompiled map with HammerPatch.
